# Generated by Django 5.0.4 on 2024-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
