# Generated by Django 5.0.4 on 2024-04-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enrollment_images/'),
        ),
    ]
