# Generated by Django 5.0.4 on 2024-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_enrollment_transaction_id_enrollment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='image',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
