# Generated by Django 5.0.4 on 2024-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_enrollment_image_enrollment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enrollment_images/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
