# Generated by Django 5.0.4 on 2024-04-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_enrollment_image_alter_enrollment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='image',
        ),
    ]
